### ISSUE TITLE
firmware ？

### ISSUE THREAD

**Issue by YCF** [Durburz/interphase#1]
I found that the matrix of your keyboard is different from the mitosis, you are using the matrix scan method just like the common keyboard. Do you have the firmware of this keyboard?

**Comment by Durburz** [comment]
Yeah, due to the fact, that there are too few IO ports at the nrf51822 I had to use a matrix design.
I'm going to start working on the firmware, when my prototype PCB arrives.

But I think I won't go reversebias' way of using QMK and a receiver. Instead i'm going to make a BLE HID firmware.

**Comment by Durburz** [comment]
Modified Mitosis firmware for matrix scanning as requested can be found here:
https://github.com/Durburz/interphase-firmware

**Comment by YCF** [comment]
Good job!
Thank you.

**Comment by jhbruhn** [comment]
"Instead i'm going to make a BLE HID firmware."
I am wondering, did that ever happen? :)

**Comment by Durburz** [comment]
No, this didn't happen on my side. But [here](https://github.com/joric/bluetosis) is a bluetooth firmware for the pretty similar mitosis keyboard.
