### ISSUE TITLE
Libraries missing

### ISSUE THREAD

**Issue by lemmi** [Durburz/interphase#2]
Hi,
wanted to check out the project, but a couple of libs seem to be missing. 

* `kicad_lib` (actually found that on your github, but it used an absolute path)
* `kicad-library-master/library/switches`
* `kicadlib-master/library/mcp1640`

It would be awesome if you made them available or could point me to where they are available. Thanks :)

**Comment by Durburz** [comment]
Hi,
sorry for the inconvenience, here are the libraries for now. I'll set them up as submodules next week.
https://github.com/oyvindt/kicadlib (mcp1640)
https://github.com/bfrigon/kicad-library (switches)

**Comment by lemmi** [comment]
perfect, thank you :)

**Comment by Durburz** [comment]
Kicad libraries are now added as git submodules.

Now it is just needed to go into the lib/*submodule* folders and execute
`git submodule init`
`git submodule update`
